baseURL = 'https://pororocomel.github.io/travel/'
languageCode = 'en-us'
title = 'Explore Royal Belum'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

relativeURLs = true

